- name: Add the serveradmin user to a server
  hosts: "debian"
  become: true
  vars_files:
    - user-data.yaml
  tasks:
    - name: Add the serveradmin user
      ansible.builtin.user:
        name: serveradmin
        uid: 1000
        groups: adm, sudo, plugdev, netdev
        append: true
        state: present
        createhome: true
        shell: /bin/bash
        home: /home/serveradmin
        password: {{ secret_user_password }}
    - name: Add .ssh directory
      ansible.builtin.file:
        path: "/home/serveradmin/.ssh"
        state: directory
        mode: '700'
        owner: serveradmin
        group: serveradmin
    - name: Copy the public ssh keyfile
      ansible.builtin.template:
        src: authorized_keys
        dest: "/home/serveradmin/.ssh/authorized_keys"
        owner: serveradmin
        group: serveradmin
        mode: '600'
