- name: Check if restart is required
  hosts: all
  tasks:
    - name: Check that the reboot-required exists
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: p
    - name: Print reboot required message if needed
      ansible.builtin.debug:
        msg: "Reboot required"
      when: p.stat.exists
