- name: Update, upgrade and install base packages
  hosts: "build_debian"
  tasks:
    - name: Update the cache
      ansible.builtin.apt:
        update_cache: true
    - name: Install base build packages
      ansible.builtin.apt:
        pkg:
          - build-essential
          - curl
          - tree
          - sudo
          - vim
          - samba
          - smbclient
          - software-properties-common
          - chrony
        state: present
      become: true
