- name: Update, upgrade and install base packages
  hosts: "debian"
  tasks:
    - name: Update the cache
      ansible.builtin.apt:
        update_cache: true
        name: "*"
        state: latest
        only_upgrade: "true"
    - name: Install base build packages
      ansible.builtin.apt:
        pkg:
          - build-essential
          - tree
          - sudo
          - vim
          - samba
          - smbclient
          - chrony
        state: present
      become: true
