- name: Update, upgrade and install base packages
  hosts: "debian"
  tasks:
    - name: update the cache
      ansible.builtin.apt:
        update_cache: yes
        name: "*"
        state: latest
    - name: Install base build packages
      ansible.builtin.apt:
        pkg:
        - build-essential
        - tree
        - sudo
        - vim
        - samba
        - smbclient
        - chrony
        state: present
      become: true
