- name: Update apt and install base packages
  hosts: "build_debian"
  tasks:
    - name: Update the cache
      ansible.builtin.apt:
        update_cache: true
    - name: Install base build packages
      ansible.builtin.apt:
        pkg:
          - build-essential
          - curl
          - e2fsprogs
          - git
          - htop
          - samba
          - smartmontools
          - smbclient
          - software-properties-common
          - ssh-import-id
          - sudo
          - tmux
          - tree
          - vim
        state: present
      become: true
