- name: Install latest qemu-guest-agent
  hosts: "ubuntu"
  tasks:
    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
      become: true
