- name: Reboot a server or group of servers
  hosts: "*"
  become: true
  tasks:
    - name: Reboot a slow machine that may have a lot of updates to apply
      ansible.builtin.reboot:
        reboot_timeout: 3600
