- name: Set timezone and configure timesyncd
  hosts: "*"
  become: true
  tasks:
    - name: Set timezone
      ansible.builtin.command:
        cmd: timedatectl set-timezone Australia/Sydney
      register: time_output
      changed_when: time_output.rc != 0

    - name: Make sure timesyncd is stopped
      ansible.builtin.systemd:
        name: systemd-timesyncd.service
        state: stopped

    - name: Copy over the timesyncd config
      ansible.builtin.template:
        src: timesyncd.conf
        dest: /etc/systemd/timesyncd.conf
        mode: '644'

    - name: Make sure timesyncd is started
      ansible.builtin.systemd:
        name: systemd-timesyncd.service
        state: started
